# render.yaml  – put this in the repo root, commit, and push
services:
  - type: web
    name: pdf-chat-backend
    env: python
    pythonVersion: 3.11          # stays on a stable runtime
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS false

    envVars:
      - key: OPENAI_API_KEY
        sync: false              # set in dashboard or env‑group
      - key: PINECONE_API_KEY
        sync: false
